server:
  port: 7002
  use-forward-headers: true

spring:
  application:
    name: api-gateway
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
zuul:
  ignoredServices: '*'
  sensitive-headers: Access-Control-Allow-Origin, Cookie,Set-Cookie
  routes:
    micro-third: /third/**
    micro-auth:
      path: /auth/**
      strip-prefix: true
  add-proxy-headers: true
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    max-per-route-connections: 200
  retryable: true
  semaphore:
    max-semaphores: 30000

ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 2
  ServerListRefreshInterval: 2000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 50000
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://admin:123456@localhost:7000/eureka/

security:
  oauth2:
    client:
      client-id: client
      client-secret: 123456
      grant-type: client_credentials
    resource:
      token-info-uri: http://192.168.40.231:7002/auth/oauth/check_token
      jwt:
        key-uri: http://127.0.0.1:7001/oauth/token_key
        key-value:

logging:
  config: classpath:log4j2-test.yml
xw:
  allowedOrigin: https://test1.xwtec.cn