Configuration:
  status: warn
 
  Properties: # 定义全局变量
    Property: # 缺省配置（用于开发环境）。其他环境需要在VM参数中指定，如下：
      - name: log.path
        value: logs
      - name: project.name
        value: base-auth
  
  Appenders:
    Console:  #输出到控制台
      name: CONSOLE
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "%highlight{%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36}.%M():%L - %msg%n}"
    RollingRandomAccessFile: # 输出到文件，超过128MB归档
      - name: ROLLING_FILE
        immediateFlush: true
        bufferedIO: true
        bufferSize: 512
        fileName: ${log.path}/${project.name}.log
        filePattern: "${log.path}/%d{yyyy-MM}/${project.name}-%d{yyyyMMdd}.log.gz"
        PatternLayout:
          pattern: "%highlight{%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36}.%M():%L - %msg%n}"
        Policies:
          TimeBasedTriggeringPolicy:
            modulate: true
            interval: 1
 
  Loggers:
    Root:
      level: info
      AppenderRef:
        - ref: CONSOLE
        - ref: ROLLING_FILE
    Logger: # 为com.xjj包配置特殊的Log级别，方便调试
      - name: com.yqq
        additivity: false
        level: debug
        AppenderRef:
          - ref: CONSOLE
          - ref: ROLLING_FILE
      - name: org.springframework
        additivity: false
        level: info
        AppenderRef:
          - ref: CONSOLE
          - ref: ROLLING_FILE
      - name: com.zaxxer
        additivity: false
        level: info
        AppenderRef:
          - ref: CONSOLE
          - ref: ROLLING_FILE
      - name: com.navercorp.pinpoint.profiler
        additivity: false
        level: info
        AppenderRef:
          - ref: CONSOLE
          - ref: ROLLING_FILE
      - name: com.navercorp.pinpoint.rpc
        additivity: false
        level: info
        AppenderRef:
          - ref: CONSOLE
          - ref: ROLLING_FILE